---
name: TSP-50-cont
cpu: No
root_dir: .
problem: "mcp" #qap, tsp, mcp
test_enabled: No

data:
    train: # Train/Val data generation parameters
        num_examples_train: 100
        num_examples_val: 100
        n_vertices: 50

        _qap:
            generative_model: ErdosRenyi # so far ErdosRenyi, Regular or BarabasiAlbert
            noise_model: ErdosRenyi
            edge_density: 0.2
            vertex_proba: 1. # Parameter of the binomial distribution of vertices
            noise: 0.05
            path_dataset: dataset_qap # Path where datasets are stored

        _tsp:
            generative_model: Square01
            distance_used: EUC_2D
            path_dataset: dataset_tsp #TSP #dataset_tsp # Path where datasets are stored

        _mcp:
            edge_density: 0.39810717055349726 #0.1
            n_vertices: 100
            clique_size: 9
            path_dataset: dataset_mcp # Path where datasets are stored
            
    test: #Test data generation parameters
        num_examples_test: 1000
        n_vertices: 50
        custom: No #If No, keeps the data_generation from train, just a failsafe so people consciouscly have to activate custom test
        
        _qap:
            generative_model: ErdosRenyi # so far ErdosRenyi, Regular or BarabasiAlbert
            noise_model: ErdosRenyi
            edge_density: 0.2
            vertex_proba: 1. # Parameter of the binomial distribution of vertices
            noise: 0.05
            path_dataset: dataset_qap # Path where datasets are stored

        _tsp:
            generative_model: Square01
            distance_used: EUC_2D
            path_dataset: dataset_tsp #TSP #dataset_tsp # Path where datasets are stored

        _mcp:
            edge_density: 0.39810717055349726 #0.1
            clique_size: 9
            path_dataset: dataset_mcp # Path where datasets are stored


train: # Training parameters
    epoch: 100
    batch_size: 16
    lr: !!float 1e-3
    scheduler_step: 1
    scheduler_factor: 0.9
    scheduler_decay: 0.9
    print_freq: 10
    loss_reduction: mean

arch: # Architecture and model
    arch: Simple_Edge_Embedding 
    model_name: Simple_Edge_Embedding #Simple_Node_Embedding
    num_blocks: 4
    original_features_num: 2
    in_features: 64
    out_features: 1
    depth_of_mlp: 3

observers:
    neptune:
        enable: No
        project: mautrib/TSP
