---
name: TSP-50-cont
cpu: Yes
root_dir: .

data: # Data related parameters
    n_vertices: 50
    path_dataset: dataset_tsp #TSP #dataset_tsp # Path where datasets are stored

train: # Training parameters
    epoch: 100
    batch_size: 1
    lr: !!float 1e-3
    scheduler_step: 1
    scheduler_decay: 0.9
    print_freq: 64

arch: # Architecture and model
    arch: Simple_Edge_Embedding 
    model_name: Simple_Edge_Embedding #Simple_Node_Embedding
    num_blocks: 4
    original_features_num: 2
    in_features: 64
    out_features: 1
    depth_of_mlp: 3

observers:
    neptune:
        enable: Yes
        project: mautrib/TSP
