---
name: Fusion
cpu: No
root_dir: .
problem: "qap" #qap, tsp, mcp, sbm
test_enabled: No

data:
    train: # Train/Val data generation parameters
        num_examples_train: 20
        num_examples_val: 10
        n_vertices: 50

        _qap:
            generative_model: ErdosRenyi # so far ErdosRenyi, Regular or BarabasiAlbert
            noise_model: ErdosRenyi
            edge_density: 0.2
            vertex_proba: 1. # Parameter of the binomial distribution of vertices
            noise: 0.05
            path_dataset: dataset_qap # Path where datasets are stored

        _tsp:
            generative_model: Square01
            distance_used: EUC_2D
            path_dataset: dataset_tsp #TSP #dataset_tsp # Path where datasets are stored

        _mcp:
            edge_density: 0.3981071705534973 #0.1
            clique_size: 9
            path_dataset: dataset_mcp # Path where datasets are stored
        
        _sbm:
            edge_density_a : 0.2
            edge_density_b : 0.3
            edge_density_link: 0.05
            path_dataset: dataset_sbm
            
    test: #Test data generation parameters
        num_examples_test: 1000
        n_vertices: 50
        custom: No #If No, keeps the data_generation from train, just a failsafe so people consciously have to activate custom test
        
        _qap:
            generative_model: ErdosRenyi # so far ErdosRenyi, Regular or BarabasiAlbert
            noise_model: ErdosRenyi
            edge_density: 0.2
            vertex_proba: 1. # Parameter of the binomial distribution of vertices
            noise: 0.05

        _tsp:
            generative_model: Square01
            distance_used: EUC_2D

        _mcp:
            edge_density: 0.39810717055349726 #0.1
            clique_size: 9
        
        _sbm:
            edge_density_a : 0.2
            edge_density_b : 0.3
            edge_density_link: 0.1


train: # Training parameters
    epoch: 20
    batch_size: 16
    lr: !!float 1e-4
    scheduler_step: 1
    scheduler_factor: 0.5
    scheduler_decay: 0.5
    print_freq: 100
    #loss_reduction: mean

arch: # Architecture and model
    arch: Siamese_Model
    model_name: Simple_Node_Embedding #Simple_Node_Embedding
    num_blocks: 5
    original_features_num: 2
    in_features: 128
    out_features: 1
    depth_of_mlp: 5

observers:
    neptune:
        enable: No
        project: mautrib/
